@startuml RockScissorPaper

object RSPGame
    object Player
        object id
        object name
        object PlayerGoals
            object play
            
    object Human
    object Computer

    object Shapes
        object rock
        object scissor
        object paper
    object Score
        object winningTimes
        object lostTimes
    object Rounds

    RSPGame *-- Player
    RSPGame *-- Rounds
    Rounds *-- Player
    RSPGame *-- Shapes
    RSPGame *-- Score

    Player *-- id
    Player *-- name
    Player *-- PlayerGoals
    Player -right-> Shapes

    PlayerGoals --> play

    Human -down-|> Player
    Computer -down-|> Player

    Shapes --> rock
    Shapes --> paper
    Shapes --> scissor

    Score --> winningTimes
    Score --> lostTimes

    Score -left-> Rounds
@enduml